version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid &&
                      RAILS_ENV=${RAILS_ENV:-development} &&
                      bundle exec rails s -b '${HOST}' -p ${PORT}"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
